name: Django CI/CD Pipeline

on:
  push:
    branches:
      -develop
      -main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -name: Checkout Code
        uses: actions/checnout@v3

      - name: Set up Python
          uses: actions/setup-python@v4
          with:
          python-version '3.9'

      - name: Install Dependancies
          run: |
          pytest --cov=. --cov-report=xml

      - name: Upload Coverage to Codcov
          uses: codecov/codecov-action@v3
          with:
          files: ./coverage.xml

deploy:
  needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Install Render CLI
         run: curl -fsSL https://render.com/deploy | bash

      - name: Deploy to Render
         env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          run: render deploy